# Generated by Django 5.2.7 on 2025-10-30 10:38

import django.db.models.deletion
import xferDxApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xferDxApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=xferDxApp.models.attachment_upload_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='xferDxApp.study')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
