# Generated by Django 5.2.7 on 2025-11-04 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xferDxApp', '0002_study_reviewed_at_study_reviewed_by_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_type', models.CharField(choices=[('CHEST', 'CHEST'), ('ABDOMEN', 'ABDOMEN'), ('EXTREMITIES', 'EXTREMITIES'), ('SKULL', 'SKULL'), ('SPINE', 'SPINE')], max_length=50)),
                ('findings', models.TextField(blank=True)),
                ('impression', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='xferDxApp.patient')),
                ('procedure_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='xferDxApp.procedureschedule')),
            ],
        ),
    ]
