# Generated by Django 5.2.7 on 2025-11-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xferDxApp', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_number',
            field=models.CharField(default='40', max_length=20),
            preserve_default=False,
        ),
    ]
