# Generated by Django 5.2.7 on 2025-11-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xferDxApp', '0004_patient_emergency_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedureschedule',
            name='procedure_type',
            field=models.CharField(choices=[('xray', 'X-Ray'), ('ct scan', 'CT Scan'), ('mri', 'MRI'), ('ultrasound', 'Ultrasound'), ('mammo', 'Mammography')], max_length=50),
        ),
    ]
