# Generated by Django 5.2.7 on 2025-11-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xferDxApp', '0005_alter_procedureschedule_procedure_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedureschedule',
            name='procedure_type',
            field=models.CharField(choices=[('xray', 'X-Ray'), ('ct', 'CT Scan'), ('mri', 'MRI'), ('ultrasound', 'Ultrasound'), ('mammo', 'Mammography')], max_length=50),
        ),
    ]
