# Generated by Django 5.2.7 on 2025-11-10 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xferDxApp', '0008_alter_procedureschedule_procedure_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='procedure_type',
        ),
    ]
