# Generated by Django 5.2.7 on 2025-11-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xferDxApp', '0009_remove_report_procedure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
